// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfrtakkvnkwxmervjozd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmcnRha2t2bmt3eG1lcnZqb3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjA0MDMsImV4cCI6MjA3MzA5NjQwM30.xIZ_vH4lIZcQWSZmo9ebcx0d_3MSG4L8IfLXpfu08EU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});